/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class Library {
	
	/* Add this function */
	public static void main(String arg[]) {
		Library lib = new Library();
		System.out.println("Hello, Cherry");
	}

	public boolean someLibraryMethod() {
        return true;
    }
}
